import { ThemeConfig } from '@regen-design/types'
import { useTheme as useThemeFn } from 'styled-components'
export const useTheme = useThemeFn as () => ThemeConfig
export * from './animations'
export * from './avatar'
export * from './button'
export * from './card'
export * from './checkbox'
export * from './checkboxGroup'
export * from './codeBlock'
export * from './common'
export * from './datePicker'
export * from './descriptions'
export * from './empty'
export * from './gradientText'
export * from './grid'
export * from './gridItem'
export * from './icon'
export * from './input'
export * from './radio'
export * from './radioGroup'
export * from './rate'
export * from './select'
export * from './slider'
export * from './space'
export * from './switch'
export * from './table'
export * from './tag'
export * from './variable'
export * from './wave'
