import { ThemeConfig } from '@regen-design/types'
export declare const useTheme: () => ThemeConfig
export * from './animations'
export * from './button'
export * from './codeBlock'
export * from './grid'
export * from './gridItem'
export * from './icon'
export * from './space'
export * from './variable'
export * from './wave'
