import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  guideSidebar: [
    {
      type: 'autogenerated',
      dirName: 'guide',
    },
  ],
  componentsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'components',
    },
  ],
}

export default sidebars
